// src/components/header.tsx
import React from "react";

//@ts-ignore
import {header, headerInner, logo, small, title} from "./header.module.scss";

interface HeaderProps {
	title: string,
}

function Header(props: HeaderProps) {
	return (
		<>
			<div className={logo}>
			</div>
			<div className={header}>
				<div className={headerInner}>
					<a href="/">
						<img src="/images/icon.png" alt="Silicon Logo"/>
					</a>
					<div className={title}>
						<h1>{props.title}</h1>
					</div>
					<a href="https://twitter.com/Redfire75369">
						<img src="/images/twitter.png" alt="Twitter" className={small}/>
					</a>
					<a href="https://mastodon.online/@redfire" rel="me">
						<img src="/images/mastodon.png" alt="Mastodon" className={small}/>
					</a>
				</div>
				<hr/>
			</div>
		</>
	);
}

export default Header;

// src/components/Header.svelte
<style lang="scss">
	$width: max(80vw, min(95vw, 700px));

	.header {
		min-width: $width;
		max-width: $width;
		margin: 0.5rem 0;

		.header-inner {
			display: flex;
			flex-direction: row;
			justify-content: start;

			a {
				display: flex;
				flex-direction: row;
				margin-left: 0.25rem;
				margin-right: 0.25rem;

				img {
					margin-top: 0.5rem;
					align-self: center;
					justify-self: center;
					height: 5rem;
					width: 5rem;
				}

				img.small {
					height: 2.25rem;
					width: 2.25rem;
				}
			}

			.title {
				text-align: center;
				min-width: calc(#{$width} - 11rem);
				max-width: calc(#{$width} - 11rem);

				h1 {
					font-size: 2.5rem;
					color: #E5E7EB;
				}
			}
		}
	}
</style>

<div class="header">
	<div class="header-inner">
		<a href="/">
			<img src="/images/icon.png" alt="Silicon Logo">
		</a>
		<div class="title">
			<h1>
				<slot/>
			</h1>
		</div>
		<a href="https://mastodon.online/@redfire" rel="me">
			<img src="/images/mastodon.png" alt="Mastodon Logo" class="small">
		</a>
	</div>
</div>
