// src/components/meta.tsx
import * as React from "react"
import {Helmet} from "react-helmet";
import {graphql, useStaticQuery} from "gatsby";

export interface MetaProps {
	author: string,
	description?: string,
	icon?: string,
	title?: string,
}

function Meta({author, description, icon, title}: MetaProps) {
	const data = useStaticQuery(graphql`
		query {
			site {
				siteMetadata {
					icon
					title
				}
			}
		}
	`);

	const pageTitle = title || data.site.siteMetadata.title;
	const pageIcon = icon || data.site.siteMetadata.icon;

	return (
		<Helmet>
			<meta charSet="utf-8"/>

			<title>{pageTitle}</title>
			<meta name="author" content={author}/>
			<link rel="icon" href={pageIcon}/>

			<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
			<meta name="robots" content="index, follow"/>

			<meta name="description" content={description || ""}/>
			<meta name="theme-color" content="#000000"/>

			<meta property="og:type" content="game"/>
			<meta property="og:title" content={pageTitle}/>
			<meta property="og:description" content={description || ""}/>
			<meta property="og:url" content="https://silicon.redfire.dev/"/>

			<meta property="twitter:title" content={pageTitle}/>
			<meta property="twitter:description" content={description || ""}/>
			<meta property="twitter:url" content="https://silicon.redfire.dev/"/>
		</Helmet>
	);
}

export default Meta;

// src/components/Meta.svelte
<script lang="ts">
	export let title: string;
	export let author: string;
	export let type: string | undefined = undefined;
	export let icon: string | undefined = undefined;
	export let description: string | undefined = undefined;
	export let tags: string[] | undefined = undefined;
	export let slug: string | undefined = undefined;
</script>

<svelte:head>
	<title>{title}</title>
	<meta property="og:title" content={title}/>
	<meta property="twitter:title" content={title}/>

	<meta name="author" content={author}/>
	<meta property="og:author" content={author}/>

	{#if type !== undefined}
		<meta property="og:type" content={type}/>
		{#if type === "article"}
			<meta property="article:section" content="Technology"/>
		{/if}
	{:else}
		<meta property="og:type" content="website"/>
	{/if}

	{#if icon !== undefined}
		<link rel="icon" href={icon}/>
	{:else}
		<link rel="icon" href="/favicon.ico"/>
	{/if}

	{#if description !== undefined}
		<meta property="description" content={description}/>
		<meta property="og:description" content={description}/>
		<meta property="twitter:description" content={description}/>
	{/if}

	{#if tags !== undefined}
		{#if tags.length !== 0}
			<meta name="keywords" content={tags.join(", ")}/>
		{/if}
		{#if type === "article"}
			{#each tags as tag}
				<meta property="article:tag" content={tag}/>
			{/each}
		{/if}
	{/if}

	{#if slug !== undefined}
		<meta property="og:url" content={`https://silicon.redfire.dev/${slug}`}/>
		<meta property="twitter:url" content={`https://silicon.redfire.dev/${slug}`}/>
	{/if}
</svelte:head>
